version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.0

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Run Tests
          command: npm test

  sonarcloud-scan:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - run:
          name: SonarCloud Scan
          command: |
            npm install -g sonarqube-scanner
            sonar-scanner \
              -Dsonar.organization=${SONARCLOUD_ORG_KEY} \
              -Dsonar.projectKey=${SONARCLOUD_PROJECT_KEY} \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${SONARCLOUD_TOKEN}

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - sonarcloud-scan
