version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      # ... Other build steps ...

  sonarcloud-scan:
    docker:
      - image: circleci/node:14

    steps:
      - run:
          name: SonarCloud Scan
          command: |
            npm install -g sonarqube-scanner
            sonar-scanner \
              -Dsonar.organization=${SONARCLOUD_ORG_KEY} \
              -Dsonar.projectKey=${SONARCLOUD_PROJECT_KEY} \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${SONARCLOUD_TOKEN}

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - sonarcloud-scan
